name: build
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v1
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19.2"

      - name: Update go deps
        run: go mod tidy

      - name: install go mock
        run: go install github.com/golang/mock/mockgen@v1.6.0

      - name: install go-junit
        run: go get -u github.com/jstemmer/go-junit-report

      - name: run tests
        run: make test

      - name: build executable
        run: make build; ls; ls bin
      
      
      
      
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.OU_REG_USER }}
          password: ${{ secrets.OU_REG_PASSWORD }}
      
      
      
      
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "."
          push: true
          tags: ${{ secrets.OU_CONTAINER_DEST }}
          