name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Update go deps
        run: go mod tidy

      - name: install go mock
        run: go install github.com/golang/mock/mockgen@v1.6.0

      - name: install go-junit
        run: go get -u github.com/jstemmer/go-junit-report

      - name: run unit tests
        run: make test

      - name: Create Tag
        id: tag
        run: echo "tag=${{ github.ref_name }}-$(git rev-parse --short HEAD)-$(date +%s)" >> $GITHUB_OUTPUT

      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          tags: improwised/kube-oidc-proxy:${{ steps.tag.outputs.tag }}
